[theme]
primaryColor = "#ff5c5c"  # Rouge personnalisé pour le menu et les boutons
backgroundColor = "#8f8787"  # Gris personnalisé pour l'arrière-plan de la page
secondaryBackgroundColor = "#ff5c5c"  # Rouge personnalisé pour la barre latérale
textColor = "black"  # Texte en noir
font = "sans serif"  # Optionnel: personnalisation de la police
